apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: staging
  app.kubernetes.io/version: "1.0"

namespace: playground-staging

resources:
- ../../base

images:
- name: gcr.io/substrateplayground-252112/jeluard/substrate-playground-server
  digest: sha256:9d2ff79cb85e1755c27700e7d831384ff46d40d0882aa0d7b8f8f14a1549ef4c
- name: gcr.io/substrateplayground-252112/jeluard/substrate-playground-ui
  digest: sha256:9d2ff79cb85e1755c27700e7d831384ff46d40d0882aa0d7b8f8f14a1549ef4c

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: playground-staging.substrate.dev
    - op: replace
      path: /spec/tls/0/hosts/0
      value: '*.playground-staging.substrate.dev'
  target:
    group: extensions
    kind: Ingress
    name: ingress
    version: v1beta1

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Service
  metadata:
    name: ingress-nginx
    namespace: ingress-nginx
  spec:
    loadBalancerIP: 34.69.4.59
